timezone: "Asia/Novosibirsk"
db:
    user: root
    password: root
    host: localhost
    database: casino
    names: utf8
    port: 5432
api:
    1:
        url: https://rublet.ru/soap/afcservice.php
        login: admin
        password: 9823jawafawf
        hash: qwerty
amqp:
    host: 127.0.0.1
    port: 5672
    user: guest
    password: guest
mb:
    exchange: casino
consumer:
    host: casino.local
    port: 8099
    event_name: offer
    lock: /tmp/offer.lock
    interval: 60
    threads: 5
    limit: 100
statsd:
    host: 127.0.0.1
    port: 8125
    prefix: "test."
    interval: 10
